FROM oven/bun:1.3.11 AS builder

WORKDIR /build

COPY . .

RUN --mount=type=cache,target=/build/node_modules bun install --frozen-lockfile
RUN --mount=type=cache,target=/build/node_modules bun run --bun check
RUN --mount=type=cache,target=/build/node_modules bun run --bun build

FROM oven/bun:1.3.11-distroless

WORKDIR /app

COPY --from=builder --chown=trinette /build/build /app

ENV ORIGIN=http://localhost:3000

CMD ["index.js"]
